title: Miras
email: your-email@example.com
description: >-
  Haftalık dijital dergi - Güncel köşe yazıları ve makaleler.
baseurl: ""
url: "https://miras.github.io"
github_username: burak

remote_theme: "mmistakes/minimal-mistakes"

# Gerekli eklentiler
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - github-pages

# Koleksiyonlar (Kategoriler)
collections:
  makaleler:
    output: true
    permalink: /makaleler/:path/
  kose-yazilari:
    output: true
    permalink: /kose-yazilari/:path/

# Sayfa numaralandırma (pagination)
paginate: 5
paginate_path: "/page:num/"

# Markdown ve Kod Vurgulama Ayarları
markdown: kramdown
highlighter: rouge

# Varsayılan Sayfa Düzeni
defaults:
  - scope:
      path: ""
      type: "makaleler"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "kose-yazilari"
    values:
      layout: "post"
